# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: sonarscanner-dotnet
      uses: np-13/sonarscan-dotnet@v0.1.0
      with:
          sonarProjectKey: jeroenlooijtu_Softwareontwerp-en-architectuur
    # The name of the SonarQube project
          sonarProjectName: Softwareontwerp-en-architectuur
    # The name of the SonarQube organization in SonarCloud. For hosted SonarQube, skip this setting.
          sonarOrganization: jeroenlooijtu
    # .NET SDK version to be used with the project
    # Optional command arguments to 'dotnet build'
