# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: install coverage
    - run: dotnet tool install --global dotnet-coverage 
    - name: Build
      run: dotnet sonarscanner begin /k:jeroenlooijtu_Softwareontwerp-en-architectuur
          /d:sonar.token=${{ secrets.SONAR_TOKEN }}
          /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
          dotnet build --no-incremental
          dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
          dotnet sonarscanner end /d:sonar.token=${{ secrets.SONAR_TOKEN }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
